management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

# Everything above these dashes will be applied to all profiles
---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:otterandcow.com.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: otterandcow.com
